{
    "name": "hr_hospital",
    "version": "16.0.1.0.0",
    "category": "Automation",
    "summary": "Keeping records of doctors and patients",
    "license": "LGPL-3",
    "author": "Odoo Community Association (OCA), Oleg Usenko",
    "website": "https://github.com/Glasis9/my_custom_addon_for_odoo_16",
    "data": [
        "security/ir.model.access.csv",
        "views/hospital_menus.xml",
        "views/hospital_doctor_views.xml",
        "views/hospital_patient_views.xml",
        "views/hospital_disease_category_views.xml",
        "views/hospital_disease_views.xml",
        "views/hospital_diagnosis_views.xml",
        "views/hospital_contact_person_views.xml",
        "views/hospital_patient_visit_views.xml",
        "views/hospital_history_of_changing_personal_doctor_views.xml",
        "views/hospital_allocation_doctor_views.xml",
        "wizard/hospital_add_comment_diagnosis_views.xml",
    ],
    "depends": ["base"],
    "demo": [
        "data/hospital_disease_category_demo.xml",
        "data/hospital_disease_demo.xml",
        "data/hospital_doctor_demo.xml",
        "data/hospital_contact_person_demo.xml",
        "data/hospital_patient_demo.xml",
        "data/hospital_diagnosis_demo.xml",
        "data/hospital_patient_visit_demo.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
