{
    "name": "beauty_salon",
    "version": "16.0.1.0.0",
    "category": "Automation",
    "summary": "Automation of business processes in a beauty salon",
    "license": "LGPL-3",
    "author": "Oleg Usenko",
    "website": "https://github.com/Glasis9/my_custom_addon_for_odoo_16",
    "depends": ["base"],
    "data": [
        "security/beauty_salon_groups.xml",
        "security/ir.model.access.csv",
        "security/beauty_salon_security.xml",
        "views/beauty_salon_menus.xml",
        "views/beauty_master_views.xml",
        "views/beauty_client_views.xml",
        "views/beauty_service_category_views.xml",
        "views/beauty_service_views.xml",
        "views/beauty_client_visit_views.xml",
        "views/beauty_master_schedule_views.xml",
        "wizard/beauty_find_out_discount_wizard_views.xml",
        "wizard/beauty_sign_up_master_wizard_views.xml",
        "wizard/beauty_client_visit_report_wizard_views.xml",
        "report/beauty_master_report.xml",
        "data/beauty_service_category_data.xml",
        "data/beauty_service_data.xml",
    ],
    "demo": [
        "demo/beauty_master_demo.xml",
        "demo/beauty_client_demo.xml",
        "demo/beauty_client_visit_demo.xml",
        "demo/beauty_master_schedule_demo.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
